version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: chewy
    versions:
    - "> 0.9.0"
  - dependency-name: doorkeeper
    versions:
    - "< 6"
    - ">= 5.a"
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: stripe
    versions:
    - "> 3.15.0"
