default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40 %>
  variables:
    lock_timeout: 3s

development:
  <<: *default
  database: kitsu_development

test:
  <<: *default
  database: kitsu_test

production:
  <<: *default
  database: kitsu_production
