default: &default
  adapter: postgresql
  encoding: unicode
<% unless $0.include?('sidekiq') %>
  pool: 40 # Concurrency from sidekiq.yml
<% else %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40 %>
<% end %>
<% unless $0.include?('rake') || $0.include?('sidekiq') %>
  connect_timeout: 5
  checkout_timeout: 2
  variables:
    lock_timeout: 6s
    statement_timeout: 15s
<% end %>

development:
  <<: *default
  database: kitsu_development

test:
  <<: *default
  database: kitsu_test

production:
  <<: *default
  database: kitsu_production
